# 条件判定による例外の置き換え
* 例外を発生させているが、本来は呼び出し側が先にチェックすべきである
* 最初に条件判定をするように呼び出し側を修正する

```java
double getValueForPeriod(int periodNumber) {
    try {
        return _values[periodNumber];
    } catch (ArrayIndexOutBoundsException e) {
        return 0;
    }
}

=>

double getValueForPeriod(int periodNumber) {
    if(periodNumber >= _values.length) {
        return 0;
    }
    return _values[periodNumber];
}
```
* 例外を条件式にするってこと？

## 例

```java
class ResourcePool
    Resource getResource() {
        Resource result;
        try {
            result = (Resource) _available.pop();
            _allocated.push(result);
            return result;
        } catch(EmptyStackException e) {
            result = new Resource();
            _allocated.push(result);
            return result;
        }
    }
    Stack _available;
    Stack _allocated;
```
* Stackの中にないのは予期せぬ自体ではない

### 1 例外を排除

```java
class ResourcePool
    Resource getResource() {
        Resource result;
        if(_available.isEmpty()) {
            result = new Resource();
            _allocated.push(result);
            return result;
        } else {
            try{
                result = (Resource) _available.pop();
                _allocated.push(result);
                return result;
            } catch(EmptyStackException e) {
                result = new Resource();
                _allocated.push(result);
                return result;
            }
        }
    }
    Stack _available;
    Stack _allocated;
```
### 2 表明の追加

```java
class ResourcePool
    Resource getResource() {
        Resource result;
        if(_available.isEmpty()) {
            result = new Resource();
            _allocated.push(result);
            return result;
        } else {
            try{
                result = (Resource) _available.pop();
                _allocated.push(result);
                return result;
            } catch(EmptyStackException e) {
                Assert.shouldNeverReachHere("使用可能な資源がなかった");
                result = new Resource();
                _allocated.push(result);
                return result;
            }
        }
    Stack _available;
    Stack _allocated;
}

class Assert {
    static void shouldNeverReachHere(String message) {
        throw new RuntimeException(message);
    }
}
```

### 3 コンパイルとテストが通ればtry節は削除

```java
class ResourcePool
    Resource getResource() {
        Resource result;
        if(_available.isEmpty()) {
            result = new Resource();
            _allocated.push(result);
            return result;
        } else {
            result = (Resource) _available.pop();
            _allocated.push(result);
            return result;
        }
    Stack _available;
    Stack _allocated;
}
```
